INSERT INTO produtos
(nome, desc_produto, preco, categoria, disponibilidade)
VALUES
(
'Skate Street Black',
'Skate ideal para manobras urbanas e street.',
300.00,
'Skate Completo',
TRUE
),
(
'Skate Fire Wheels',
'Modelo com rodas de alta resistência e velocidade.',
250.00,
'Skate Completo',
TRUE
),
(
'Godoflip Classic',
'Modelo clássico da Godoflip para iniciantes e intermediários.',
220.00,
'Skate Completo',
TRUE
),
(
'Urban Skate Pro',
'Skate profissional para uso urbano e pistas.',
380.00,
'Skate Completo',
TRUE
),
(
'Flip Dark Edition',
'Edição especial com design escuro exclusivo.',
365.00,
'Skate Completo',
TRUE
);



INSERT INTO img_produtos
(produto_id, url)
VALUES
(1, 'imagens/skate1_angulo1.webp'),
(2, 'imagens/skate2_angulo1.webp'),
(3, 'imagens/skate3_angulo01.webp'),
(4, 'imagens/skate4_angulo1.webp'),
(5, 'imagens/skate5_angulo1.webp');